version: "3.7"
services:
  imagebuild:
    image: orbital-debian-image
    privileged: true
    entrypoint:  ./startup.sh
    build:
      context: debian
      dockerfile: Dockerfile
    environment:
      USE_QCOW2: 0
      BASE_QCOW2_SIZE: "12G"
      IMG_NAME: Orbital-Image
      RELEASE: buster
      LOCALE_DEFAULT: en_GB.UTF-8
      TARGET_HOSTNAME: orbitalteapot
      KEYBOARD_KEYMAP: "gb"
      KEYBOARD_LAYOUT: "English (UK)"
      TIMEZONE_DEFAULT: UTC
      FIRST_USER_NAME: yourusername
      FIRST_USER_PASS: supersecretpassword
      WPA_ESSID: yourssid
      WPA_PASSWORD: yourwifipassword
      WPA_COUNTRY: gb
      ENABLE_SSH: 1 # 0 or 1
      PUBKEY_SSH_FIRST_USER: ""
      PUBKEY_ONLY_SSH: 0 # 0 or 1
      STAGE_LIST: stage* # Define stages you want to run
    cap_add:
      - SYS_CHROOT

    volumes: 
    - type: bind
      source: /home/username/deploy/ # Your pi images will end up here
      target: /build/pi-gen/deploy/
